#pragma once
#define MOD_NODE_CONFIG_CLUSTER 0xFC10
#define MOD_NODE_CONFIG_EP 1
#define MOD_NODE_CMD_GET_INFO 0x01
#define MOD_NODE_CMD_GET_CHANNEL 0x02
#define MOD_NODE_CMD_SET_NAME 0x10
#define MOD_NODE_CMD_SET_CHANNEL 0x11
#define MOD_NODE_CMD_APPLY_REBOOT 0x12
#define MOD_NODE_CMD_FACTORY_RESET 0x13
#define MOD_NODE_CMD_SET_STATUS_LED 0x14
#define MOD_NODE_CMD_SET_POLL 0x15 /* [channel][seconds:2BE], protocol >= 3 */
#define MOD_NODE_RSP_INFO 0x81
#define MOD_NODE_RSP_CHANNEL 0x82
#define MOD_NODE_RSP_STATUS 0x90
